### ISSUE TITLE
 能不能升级下版本，顺便做个elk的版本

### ISSUE THREAD

**Issue by ExtremeYu** [sxyx2008/solrj-example#2]

**Comment by v5tech** [comment]
@ExtremeYu 工作太忙，暂时没有升级计划。elk比Solr简单，jd页面布局元素可能有调整，修改下webmagic爬虫部分代码。elk有jdbc导入插件，可以针对数据库表进行索引。当然爬虫部分代码可以改用python来爬，webmagic有点重了。elasticsearch搜素可以使用REST API或者jest或者Spring Data Elasticsearch来处理。
相关示例如下
https://github.com/ameizi/elasticsearch 集成好各种插件的elasticsearch，可在本地直接运行
https://github.com/ameizi/spring-data-elasticsearch-example spring-data-elasticsearch案例
https://github.com/ameizi/elasticsearch-jest-example jest操作elasticsearch案例
https://github.com/ameizi/elasticsearch/issues/3 elasticsearch-jdbc 插件使用

**Comment by ExtremeYu** [comment]
搞了一下，不太好弄。。。

**Comment by ExtremeYu** [comment]
老哥你是西安的？
